name: Verifiable Actions

on: [push]

# on:
#   workflow_dispatch:

jobs:
  issue_credential:
    name: A job to issue a verifiable credential
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2

      - name: Issue a Verifiable Credential
        id: credential_issue
        uses: transmute-industries/verifiable-actions@v0.0.4
        with:
          resource: "credential"
          action: "issue"
          verification-method: "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn"
          # always use github secrets for this... treat it like a private key.
          mnemonic: "${{ secrets.MNEMONIC }}"
          # These are defaults, un comment to change
          # hd-path: "m/44'/0'/0'/0/0"
          # key-type: "ed25519"
          # vc-format: "vc"

          file-input: "./test/data/credential.json"
          file-output: "./test/data/verifiable-credential.json"

      - name: View Verifiable Credential
        run: cat "./test/data/verifiable-credential.json"

      - uses: actions/cache@v2
        id: cache-issued
        with:
          path: |
            ./*
          key: ${{ github.sha }}

  verify_credential:
    name: A job to verify a verifiable credential
    concurrency: verify_credential
    needs:
      - issue_credential
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Verify a Verifiable Credential
        id: credential_verify
        uses: transmute-industries/verifiable-actions@v0.0.4
        with:
          resource: "credential"
          action: "verify"

          vc-verify-endpoint: "https://api.did.actor/api/credentials/verify"

          file-input: "./test/data/verifiable-credential.json"
          file-output: "./test/data/verification.json"

      - name: View Verification Results
        run: cat "./test/data/verification.json"
