name: Public Credential Registry Features

on: [push]

jobs:
  issue_credential:
    name: Issue Verifiable Credential
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2

      - name: Create Issuer
        id: create_issuer
        uses: transmute-industries/verifiable-actions@v0.0.7
        with:
          resource: "did"
          action: "generate"
          username: "transmute-industries"
          repository: "verifiable-actions"
          mnemonic: "${{ secrets.MNEMONIC }}"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"
          file-output: "./test/data/issuer-0.json"

      - name: View Issuer
        run: cat "./test/data/issuer-0.json"

      # - name: Issue a Verifiable Credential
      #   id: credential_issue
      #   uses: transmute-industries/verifiable-actions@v0.0.6
      #   with:
      #     resource: "credential"
      #     action: "issue"
      #     username: "transmute-industries"
      #     repository: "verifiable-actions"
      #     mnemonic: "${{ secrets.MNEMONIC }}"
      #     hd-path: "m/44'/0'/0'/0/0"
      #     key-type: "ed25519"

      #     file-input: "./test/data/credential.json"
      #     file-output: "./test/data/verifiable-credential.json"

      # - name: View Verifiable Credential
      #   run: cat "./test/data/verifiable-credential.json"

      # - uses: actions/cache@v2
      #   id: cache-issued
      #   with:
      #     path: |
      #       ./*
      #     key: ${{ github.sha }}
