name: Verifiable Actions

on: [push]

# on:
#   workflow_dispatch:

jobs:
  issue_credential:
    runs-on: ubuntu-latest
    name: A job to issue a verifiable credential
    steps:
      - name: checking out repo
        uses: actions/checkout@v2

      - name: Issue a Verifiable Credential
        id: credential_issue
        uses: transmute-industries/verifiable-actions@v0.0.4
        with:
          resource: "credential"
          action: "issue"

          mnemonic: "sell antenna drama rule twenty cement mad deliver you push derive hybrid"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"

          vc-format: "vc"

          file-input: "./test/data/credential.json"
          file-output: "./test/data/verifiable-credential.json"

      - name: View Verifiable Credential Issuer
        run: echo "Issuer was ${{ steps.credential_issue.outputs.issuer.id }}"

      - name: Verify a Verifiable Credential
        id: credential_verify
        uses: transmute-industries/verifiable-actions@v0.0.4
        with:
          resource: "credential"
          action: "verify"

          vc-verify-endpoint: "https://api.did.actor/api/credentials/verify"

          file-input: "./test/data/verifiable-credential.json"
          file-output: "./test/data/verification.json"

      - name: View Verification Results
        run: echo "Verification was ${{ steps.credential_verify.outputs.verified }}"
